# Generated by Django 4.1.5 on 2023-01-21 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Quote ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        choices=[("Basic", "Basic"), ("Premium", "Premium")],
                        max_length=7,
                        verbose_name="Coverage Type",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("CA", "California"),
                            ("NY", "New York"),
                            ("TX", "Texas"),
                        ],
                        max_length=2,
                        verbose_name="State",
                    ),
                ),
                ("pet", models.BooleanField(default=False)),
                (
                    "flood_coverage",
                    models.BooleanField(default=False, verbose_name="Flood Coverage"),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Total"
                    ),
                ),
                (
                    "monthly_tax",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Monthly Tax"
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Subtotal"
                    ),
                ),
            ],
        ),
    ]
